#!/bin/sh
set -e

if [ -e /etc/xlc.cfg ]; then
  export XL_CONFIG=/etc/xlc.cfg
fi

mkdir -p obj
xlc -c -Wc,lp64 -Wc,LIST'(./obj)' -o obj/main.o src/main.c
as --SYSPARM'(AMODE64)',LIST,SUPRWARN'(425,434)' -o obj/tester.o src/tester.s >obj/tester.alst 2>/dev/null
mkdir -p bin
xlc -Wl,LP64 -o bin/grubtest obj/main.o obj/tester.o >obj/grubtest.llst
